services:
  udp_server:
    build:
      context: ./udp_server
      dockerfile: Dockerfile
    ports:
      - "5000:5000/udp"
      
  udp_client:
    build:
      context: ./udp_client
      dockerfile: Dockerfile
    depends_on:
      - udp_server
    environment:
      - PAYLOAD_SIZE=2048
      - INTERVAL_SEC=1
